### ISSUE TITLE
puzzle_hash convert address

### ISSUE THREAD

**Issue by xianggy** [freddiecoleman/chia-client#15]
How to make a convertion between puzzle_hash and address?
Can it be provided as a tool in chia-client please?

thank you.

**Comment by oncecsc** [comment]
import { bech32m } from 'bech32';

const puzzleHashWithoutPrefix = '195564b2245bfc2ae660de78c0c02b05c975e6980d222863f2e3b68655955790';
const words = bech32m.toWords(Buffer.from(puzzleHashWithoutPrefix, 'hex'));

console.log(bech32m.encode('xch', words)); // xch1r92kfv3yt07z4enqmeuvpsptqhyhte5cp53zscljuwmgv4v427gqljwlzj

**Comment by xianggy** [comment]
Yes, got it. Thanks so much for your reply.

**Comment by 1044740162** [comment]
> Yes, got it. Thanks so much for your reply.
Hello, how should I get puzzleHashWithoutPrefix from generateMnemonic()；
I don't know the process very well, can you help me answer it?

**Comment by CMEONE** [comment]
@1044740162 I've coded a module to do it, it's publishing to NPM and then I will send the link here.

**Comment by CMEONE** [comment]
For all interested, I've created the `chia-utils` node module:
https://www.npmjs.com/package/chia-utils
https://github.com/CMEONE/chia-utils

**Comment by 1044740162** [comment]
> @ 1044740162我已经编写了一个模块来执行此操作，该模块正在发布到NPM，然后将链接发送到此处。



> @1044740162 I've coded a module to do it, it's publishing to NPM and then I will send the link here.

Yes it's very cool, thank you
